FROM python:3.10-slim

RUN apt-get update -y && apt-get install -y \
    python3-dev libcurl4-openssl-dev libgnutls28-dev python3-all-dev \
    libboost-python-dev make zlib1g-dev gcc libssl-dev git \
    && apt-get clean
RUN apt-get update -y && apt-get install --reinstall -y \
    build-essential \
    && apt-get clean

RUN pip install --upgrade pip

