version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t bladrak/thumbor-dev:latest .
          docker build -t bladrak/thumbor-dev-py3:latest -f Dockerfile-py3 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push bladrak/thumbor-dev:latest
          docker push bladrak/thumbor-dev-py3:latest
